seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    classloader-cache-mode: true
    slot-service:
      dynamic-slot: true
    http:
      enable-http: true
      port: 8080
      enable-dynamic-port: false
      port-range: 100
    checkpoint:
      interval: 300000
      timeout: 10000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot/
          storage.type: hdfs
          fs.defaultFS: file:///tmp/
    telemetry:
      metric:
        enabled: true
